# Book settings

# Learn more at https://jupyterbook.org/customize/config.html
title: Documentation
author: Broad Institute
copyright: "2022"
#logo: img/logo.svg

# Only build files that are in the ToC
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Information about where the book exists on the web
repository:
  url: https://github.com/distributed-science/distributed-cellprofiler
  branch: main  # Which branch of the repository should be used when creating links (optional)
  path_to_book: DCP-documentation

html:
  baseurl: distributedscience.github.io
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  comments:
    hypothesis: true

parse:
  myst_enable_extensions:
    # Only required if you use html <img>
    - html_image
